name: canteen_app
description: A new Flutter project for the Amrita Canteen Management System.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.5+1
  cupertino_icons: ^1.0.2

  # Add these Firebase packages
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0
  firebase_auth: ^6.3.0
  intl: ^0.20.2
  razorpay_flutter: ^1.4.3
  fluttertoast: ^9.0.0
  js: ^0.7.2
  flutter_local_notifications: ^21.0.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # This line includes all files you place in the 'assets' folder.
  assets:
    - assets/