// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbNCc0FRq3QiJW0ElJDGI8Pum-PVjMgfM',
    appId: '1:858833568685:web:37279812c09c7508a45724',
    messagingSenderId: '858833568685',
    projectId: 'amrita-canteen-app',
    authDomain: 'amrita-canteen-app.firebaseapp.com',
    storageBucket: 'amrita-canteen-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxcKVVHVGr5f6fmBUC8rAKNyzHIwRX0fk',
    appId: '1:858833568685:android:44c445b5927acc0ea45724',
    messagingSenderId: '858833568685',
    projectId: 'amrita-canteen-app',
    storageBucket: 'amrita-canteen-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVw7cX7EaHwmtxL3o06JaT2mw-kngqx2Y',
    appId: '1:858833568685:ios:bb2bdce313559bcda45724',
    messagingSenderId: '858833568685',
    projectId: 'amrita-canteen-app',
    storageBucket: 'amrita-canteen-app.firebasestorage.app',
    iosBundleId: 'com.example.canteenAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVw7cX7EaHwmtxL3o06JaT2mw-kngqx2Y',
    appId: '1:858833568685:ios:bb2bdce313559bcda45724',
    messagingSenderId: '858833568685',
    projectId: 'amrita-canteen-app',
    storageBucket: 'amrita-canteen-app.firebasestorage.app',
    iosBundleId: 'com.example.canteenAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbNCc0FRq3QiJW0ElJDGI8Pum-PVjMgfM',
    appId: '1:858833568685:web:37279812c09c7508a45724',
    messagingSenderId: '858833568685',
    projectId: 'amrita-canteen-app',
    authDomain: 'amrita-canteen-app.firebaseapp.com',
    storageBucket: 'amrita-canteen-app.firebasestorage.app',
  );
}
